"""add embedding

Revision ID: d084689f1767
Revises: 202604071200
Create Date: 2026-04-07 13:13:24.068921

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd084689f1767'
down_revision = '202604071200'
branch_labels = None
depends_on = None


from pgvector.sqlalchemy import Vector


def upgrade():
    # activer pgvector
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # created_at non nullable
    op.alter_column(
        'imageupload',
        'created_at',
        existing_type=sa.TIMESTAMP(timezone=True),
        nullable=False
    )

    # ✅ créer la colonne embedding
    op.add_column(
        'imageupload',
        sa.Column('embedding', Vector(512), nullable=True)
    )

    # index vectoriel
    op.execute("""
        CREATE INDEX ix_image_embedding
        ON imageupload
        USING ivfflat (embedding vector_cosine_ops)
        WITH (lists = 100);
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_image_embedding")

    op.execute("""
               ALTER TABLE imageupload
               ALTER
               COLUMN embedding TYPE jsonb;
               """)

    op.alter_column(
        'imageupload',
        'created_at',
        existing_type=sa.TIMESTAMP(timezone=True),
        nullable=True
    )
    # ### end Alembic commands ###
